spring.profiles.active: local
server.port: 9000

spring:
  datasource:
    prod:
      # real database
      url: url
      username: user
      password: password
      driverClassName: driver
    local:
      # localhost database in docker container
      url: jdbc:postgresql://localhost:5432/trade_center
      username: postgres
      password: movie_park_api_password
      driverClassName: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate.ddl-auto: validate

cache:
  seance_info:
    flush_timeout: 10
    flush_timeout_min: 2
    flush_timeout_max: 30
  rps:
    flush_timeout: 10
    lifetime: 120

# actuator
management:
  endpoints:
    web.base-path: /movie-park/service
#    web.exposure.include: env,info,health,httptrace,logfile,metrics,mappings
#  HEALTH ENDPOINT
  endpoint:
    health.show-details: always
  health.diskSpace.enabled: false
