spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade_center
    driver-class-name: org.postgresql.Driver
    username: login
    password: password
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate.ddl-auto: validate

server.port: 9000

max.cache.life.time: 30000
min.cache.life.time: 2000
seance.info.cache.flush.timeout: 3
rps.map.flush.timeout: 3
rps.life.time: 120

# actuator
management:
  endpoints:
    web.base-path: /movie_park_service
    #web.exposure.include: *
    # HEALTH ENDPOINT
    health.show-details: always
  health.diskSpace.enabled: false
